name: TechUpdate
favicon: null
layout_spectrum: 0.6397849
typography_spectrum: 0.003584229
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: tech
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#434341'
    - '#babec7'
    - '#060604'
    - '#a27151'
  brandStrength: 0.7060932
  lightness: 0.3835126
  saturation: 0.6935484
  rhythmicContrast: 0.2759857
purpose: []
