name: TechUpdate
favicon: null
layout_spectrum: 0.6497
typography_spectrum: 0.003584229
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1e1e'
    - '#ffffff'
    - '#5a5958'
    - '#49def8'
    - '#f70471'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0
purpose: []
